# Generated by Django 4.1 on 2023-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=' multiklar')),
                ('about', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos')),
            ],
        ),
    ]
