# Generated by Django 4.1 on 2023-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multik',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='multik',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='multik',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='multik',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' multiklar'),
        ),
        migrations.AlterField(
            model_name='multik',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
